- name: Configure development environment
  hosts: localhost

  tasks:

  - name: Configure Nushell
    ansible.builtin.copy:
      src: "{{DOTFILES_DIR}}/nushell/"
      dest: ~/.config/nushell/

  - name: Configure Alacritty
    ansible.builtin.copy:
      src: "{{DOTFILES_DIR}}/alacritty/"
      dest: ~/.config/alacritty/

  - name: Configure ZelliJ
    ansible.builtin.copy:
      src: "{{DOTFILES_DIR}}/zellij/"
      dest: ~/.config/zellij/

  - name: Configure Neovim
    ansible.builtin.copy:
      src: "{{DOTFILES_DIR}}/nvim/"
      dest: ~/.config/nvim/

